### ISSUE TITLE
There is an issue when tried to render skin and head at same time

### ISSUE THREAD

**Issue by GoodDay360** [benno1237/MinePI#4] opened 2021-07-31 20:22 UTC
The issue is I can't render my local skin. I mean the file that I downloaded on website and saved somewhere on my hard disk. Please add this feature. Thanks

**Comment by benno1237** [comment] 2021-08-01 10:32
Hi, thanks for using this tool! Could you go a bit into detail what exactly you want to see? The render functions accepts a skin_image parameter. If this is given, the skin is rendered from this pic instead of a username/uuid. You can just load your local image using pillow (PIL) and pass it on to the render function. Hope thats what you are looking for?

**Comment by GoodDay360** [comment] 2021-08-03 05:49
Yes it what am look like for. But there is an issue with head when I tried to render head and skin at the same time with loop. It look something like this:
![image](https://user-images.githubusercontent.com/59399625/127964346-c50d50db-4c70-47d1-a340-807acb82ad95.png)
![image](https://user-images.githubusercontent.com/59399625/127964371-1417b633-ecb0-44a5-a077-c47b36bd2941.png)
![image](https://user-images.githubusercontent.com/59399625/127964411-f33331bc-6f79-4e0c-ab79-c90667bf3ba4.png)
![image](https://user-images.githubusercontent.com/59399625/127964541-a892cb52-fc68-4c7e-9d0b-c8c3b53a4672.png)

**Comment by benno1237** [comment] 2021-08-04 16:50
Are you sure that this actually is an issue of my library? I am not able to reproduce the issue. Might as well be a scaling problem. Did you pay attention to the aspect ratio of the image?

**Comment by GoodDay360** [comment] 2021-08-05 00:29
@benno1237 Thank for replying, I might be dumb but I'm new to coding. sorry for asking if you already give the answer in readme. But I still don't understand the reason why it like that. I tried to add ratio = 12 like what it said in default and aa = True but the result is still the same. Is there the other way ? can you give me an example ? Thanks.

**Comment by benno1237** [comment] 2021-08-05 05:46
aa is short for antializing which does nothing but smoothen the corners a bit. Thats not really related. Ratio changes the quality in pixels but the aspect ratio is fixed. I will give it a go today and see how it behaves for me.

**Comment by GoodDay360** [comment] 2021-08-07 01:34
If my guess is right. The reason why the image aspect ratio of rendered head is like that because when you rendered 3d skin the variable in library save the aspect ratio size of 3d skin image. and when you start to render 3d head it going use aspect ratio of rendered 3d skin.( If the main script isn't restart the library not restart too so it wont reset the variable of image aspect ratio ). Maybe you should make the variable of aspect ratio reset it self when after done rendered a 3dskin or 3dhead.

**Comment by benno1237** [comment] 2021-08-09 15:42
thanks for letting me know. give me a few days please

**Comment by GoodDay360** [comment] 2021-08-15 05:14
@benno1237 Anyway I use ur Library to make this Launcher: **https://github.com/GoodDay360/Tempest-Launcher**
Hope you don't mind.

**Comment by benno1237** [comment] 2021-08-15 14:35
Your issue should hopefully be fixed now. Let me know if you still encounter some bugs please.
Whatever you use it for, I am okay with.

I am closing this issue now. Feel free to open a new one if needed

**Closed by benno1237** 2021-08-15 14:35 UTC
